//
//  LocationsDataService.swift
//  MapTest
//
//  Created by Nick Sarno on 11/26/21.
//

import Foundation
import MapKit

class LocationsDataService {
    
    static let locations: [Location] = [
        Location(
            name: "Colosseum",
            cityName: "Rome",
            coordinate: CLLocationCoordinate2D(latitude: 41.8902, longitude: 12.4922),
            description: "The Colosseum is an oval amphitheatre in the centre of the city of Rome, Italy, just east of the Roman Forum. It is the largest ancient amphitheatre ever built, and is still the largest standing amphitheatre in the world today, despite its age.",
            imageName: [
                "rome-colosseum-1",
                "rome-colosseum-2",
                "rome-colosseum-3",
            ],
            link: "https://en.wikipedia.org/wiki/Colosseum"),
        Location(
            name: "Pantheon",
            cityName: "Rome",
            coordinate: CLLocationCoordinate2D(latitude: 41.8986, longitude: 12.4769),
            description: "The Pantheon is a former Roman temple and since the year 609 a Catholic church, in Rome, Italy, on the site of an earlier temple commissioned by Marcus Agrippa during the reign of Augustus.",
            imageName: [
                "rome-pantheon-1",
                "rome-pantheon-2",
                "rome-pantheon-3",
            ],
            link: "https://en.wikipedia.org/wiki/Pantheon,_Rome"),
        Location(
            name: "Trevi Fountain",
            cityName: "Rome",
            coordinate: CLLocationCoordinate2D(latitude: 41.9009, longitude: 12.4833),
            description: "The Trevi Fountain is a fountain in the Trevi district in Rome, Italy, designed by Italian architect Nicola Salvi and completed by Giuseppe Pannini and several others. Standing 26.3 metres high and 49.15 metres wide, it is the largest Baroque fountain in the city and one of the most famous fountains in the world.",
            imageName: [
                "rome-trevifountain-1",
                "rome-trevifountain-2",
                "rome-trevifountain-3",
            ],
            link: "https://en.wikipedia.org/wiki/Trevi_Fountain"),
        Location(
            name: "Eiffel Tower",
            cityName: "Paris",
            coordinate: CLLocationCoordinate2D(latitude: 48.8584, longitude: 2.2945),
            description: "The Eiffel Tower is a wrought-iron lattice tower on the Champ de Mars in Paris, France. It is named after the engineer Gustave Eiffel, whose company designed and built the tower. Locally nicknamed 'La dame de fer', it was constructed from 1887 to 1889 as the centerpiece of the 1889 World's Fair and was initially criticized by some of France's leading artists and intellectuals for its design, but it has become a global cultural icon of France and one of the most recognizable structures in the world.",
            imageName: [
                "paris-eiffeltower-1",
                "paris-eiffeltower-2",
            ],
            link: "https://en.wikipedia.org/wiki/Eiffel_Tower"),
        Location(
            name: "Louvre Museum",
            cityName: "Paris",
            coordinate: CLLocationCoordinate2D(latitude: 48.8606, longitude: 2.3376),
            description: "The Louvre, or the Louvre Museum, is the world's most-visited museum and a historic monument in Paris, France. It is the home of some of the best-known works of art, including the Mona Lisa and the Venus de Milo. A central landmark of the city, it is located on the Right Bank of the Seine in the city's 1st arrondissement.",
            imageName: [
                "paris-louvre-1",
                "paris-louvre-2",
                "paris-louvre-3",
            ],
            link: "https://en.wikipedia.org/wiki/Louvre"),
        Location(name: "Москва", cityName: "Москва", coordinate: CLLocationCoordinate2D(latitude: 55.7558, longitude: 37.6173), description: "Столица России", imageName: ["https://source.unsplash.com/600x400/?moscow+city"], link: "https://ru.wikipedia.org/wiki/Москва"),
                Location(name: "Санкт-Петербург", cityName: "Санкт-Петербург", coordinate: CLLocationCoordinate2D(latitude: 59.9343, longitude: 30.3351), description: "Северная столица России", imageName: ["https://source.unsplash.com/600x400/?saint+petersburg"], link: "https://ru.wikipedia.org/wiki/Санкт-Петербург"),
                Location(name: "Новосибирск", cityName: "Новосибирск", coordinate: CLLocationCoordinate2D(latitude: 55.0084, longitude: 82.9357), description: "Крупнейший город Сибири", imageName: ["https://source.unsplash.com/600x400/?novosibirsk"], link: "https://ru.wikipedia.org/wiki/Новосибирск"),
                Location(name: "Екатеринбург", cityName: "Екатеринбург", coordinate: CLLocationCoordinate2D(latitude: 56.8389, longitude: 60.6057), description: "Столица Урала", imageName: ["https://source.unsplash.com/600x400/?yekaterinburg"], link: "https://ru.wikipedia.org/wiki/Екатеринбург"),
                Location(name: "Казань", cityName: "Казань", coordinate: CLLocationCoordinate2D(latitude: 55.8304, longitude: 49.0661), description: "Столица Татарстана", imageName: ["https://source.unsplash.com/600x400/?kazan"], link: "https://ru.wikipedia.org/wiki/Казань"),
                Location(name: "Нижний Новгород", cityName: "Нижний Новгород", coordinate: CLLocationCoordinate2D(latitude: 56.3269, longitude: 44.0075), description: "Город на слиянии Волги и Оки", imageName: ["https://source.unsplash.com/600x400/?nizhny+novgorod"], link: "https://ru.wikipedia.org/wiki/Нижний_Новгород"),
                Location(name: "Челябинск", cityName: "Челябинск", coordinate: CLLocationCoordinate2D(latitude: 55.1644, longitude: 61.4368), description: "Крупный промышленный центр", imageName: ["https://source.unsplash.com/600x400/?chelyabinsk"], link: "https://ru.wikipedia.org/wiki/Челябинск"),
                Location(name: "Самара", cityName: "Самара", coordinate: CLLocationCoordinate2D(latitude: 53.1959, longitude: 50.1002), description: "Город на Волге", imageName: ["https://source.unsplash.com/600x400/?samara"], link: "https://ru.wikipedia.org/wiki/Самара"),
                Location(name: "Омск", cityName: "Омск", coordinate: CLLocationCoordinate2D(latitude: 54.9893, longitude: 73.3682), description: "Город в Западной Сибири", imageName: ["https://source.unsplash.com/600x400/?omsk"], link: "https://ru.wikipedia.org/wiki/Омск"),
                Location(name: "Ростов-на-Дону", cityName: "Ростов-на-Дону", coordinate: CLLocationCoordinate2D(latitude: 47.2357, longitude: 39.7015), description: "Южная столица России", imageName: ["https://source.unsplash.com/600x400/?rostov+on+don"], link: "https://ru.wikipedia.org/wiki/Ростов-на-Дону"),
                Location(name: "Уфа", cityName: "Уфа", coordinate: CLLocationCoordinate2D(latitude: 54.7351, longitude: 55.9587), description: "Столица Башкортостана", imageName: ["https://source.unsplash.com/600x400/?ufa"], link: "https://ru.wikipedia.org/wiki/Уфа"),
                Location(name: "Красноярск", cityName: "Красноярск", coordinate: CLLocationCoordinate2D(latitude: 56.0153, longitude: 92.8932), description: "Крупнейший город Восточной Сибири", imageName: ["https://source.unsplash.com/600x400/?krasnoyarsk"], link: "https://ru.wikipedia.org/wiki/Красноярск"),
                Location(name: "Пермь", cityName: "Пермь", coordinate: CLLocationCoordinate2D(latitude: 58.0105, longitude: 56.2502), description: "Город на реке Каме", imageName: ["https://source.unsplash.com/600x400/?perm"], link: "https://ru.wikipedia.org/wiki/Пермь"),
                Location(name: "Воронеж", cityName: "Воронеж", coordinate: CLLocationCoordinate2D(latitude: 51.6720, longitude: 39.1843), description: "Колыбель русского флота", imageName: ["https://source.unsplash.com/600x400/?voronezh"], link: "https://ru.wikipedia.org/wiki/Воронеж"),
                Location(name: "Волгоград", cityName: "Волгоград", coordinate: CLLocationCoordinate2D(latitude: 48.7080, longitude: 44.5133), description: "Город-герой на Волге", imageName: ["https://source.unsplash.com/600x400/?volgograd"], link: "https://ru.wikipedia.org/wiki/Волгоград"),
                Location(name: "Краснодар", cityName: "Краснодар", coordinate: CLLocationCoordinate2D(latitude: 45.0355, longitude: 38.9753), description: "Столица Кубани", imageName: ["https://source.unsplash.com/600x400/?krasnodar"], link: "https://ru.wikipedia.org/wiki/Краснодар"),
                Location(name: "Саратов", cityName: "Саратов", coordinate: CLLocationCoordinate2D(latitude: 51.5924, longitude: 45.9608), description: "Город на Волге", imageName: ["https://source.unsplash.com/600x400/?saratov"], link: "https://ru.wikipedia.org/wiki/Саратов"),
                Location(name: "Тюмень", cityName: "Тюмень", coordinate: CLLocationCoordinate2D(latitude: 57.1613, longitude: 65.5250), description: "Нефтегазовая столица России", imageName: ["https://source.unsplash.com/600x400/?tyumen"], link: "https://ru.wikipedia.org/wiki/Тюмень"),
                Location(name: "Тольятти", cityName: "Тольятти", coordinate: CLLocationCoordinate2D(latitude: 53.5088, longitude: 49.4192), description: "Автомобильная столица", imageName: ["https://source.unsplash.com/600x400/?tolyatti"], link: "https://ru.wikipedia.org/wiki/Тольятти"),
                Location(name: "Ижевск", cityName: "Ижевск", coordinate: CLLocationCoordinate2D(latitude: 56.8527, longitude: 53.2115), description: "Оружейная столица", imageName: ["https://source.unsplash.com/600x400/?izhevsk"], link: "https://ru.wikipedia.org/wiki/Ижевск"),
                Location(name: "Барнаул", cityName: "Барнаул", coordinate: CLLocationCoordinate2D(latitude: 53.3478, longitude: 83.7798), description: "Столица Алтайского края", imageName: ["https://source.unsplash.com/600x400/?barnaul"], link: "https://ru.wikipedia.org/wiki/Барнаул"),
                Location(name: "Ульяновск", cityName: "Ульяновск", coordinate: CLLocationCoordinate2D(latitude: 54.3142, longitude: 48.4031), description: "Родина Ленина", imageName: ["https://source.unsplash.com/600x400/?ulyanovsk"], link: "https://ru.wikipedia.org/wiki/Ульяновск"),
                Location(name: "Иркутск", cityName: "Иркутск", coordinate: CLLocationCoordinate2D(latitude: 52.2864, longitude: 104.2807), description: "Ворота Байкала", imageName: ["https://source.unsplash.com/600x400/?irkutsk"], link: "https://ru.wikipedia.org/wiki/Иркутск"),
                Location(name: "Хабаровск", cityName: "Хабаровск", coordinate: CLLocationCoordinate2D(latitude: 48.4802, longitude: 135.0719), description: "Столица Дальнего Востока", imageName: ["https://source.unsplash.com/600x400/?khabarovsk"], link: "https://ru.wikipedia.org/wiki/Хабаровск"),
                Location(name: "Ярославль", cityName: "Ярославль", coordinate: CLLocationCoordinate2D(latitude: 57.6261, longitude: 39.8845), description: "Жемчужина Золотого кольца", imageName: ["https://source.unsplash.com/600x400/?yaroslavl"], link: "https://ru.wikipedia.org/wiki/Ярославль"),
                Location(name: "Владивосток", cityName: "Владивосток", coordinate: CLLocationCoordinate2D(latitude: 43.1155, longitude: 131.8855), description: "Портовый город на Тихом океане", imageName: ["https://source.unsplash.com/600x400/?vladivostok"], link: "https://ru.wikipedia.org/wiki/Владивосток"),
                Location(name: "Махачкала", cityName: "Махачкала", coordinate: CLLocationCoordinate2D(latitude: 42.9849, longitude: 47.5047), description: "Столица Дагестана", imageName: ["https://source.unsplash.com/600x400/?makhachkala"], link: "https://ru.wikipedia.org/wiki/Махачкала"),
                Location(name: "Томск", cityName: "Томск", coordinate: CLLocationCoordinate2D(latitude: 56.4846, longitude: 84.9476), description: "Научный и образовательный центр", imageName: ["https://source.unsplash.com/600x400/?tomsk"], link: "https://ru.wikipedia.org/wiki/Томск"),
                Location(name: "Оренбург", cityName: "Оренбург", coordinate: CLLocationCoordinate2D(latitude: 51.7682, longitude: 55.0969), description: "Город на границе Европы и Азии", imageName: ["https://source.unsplash.com/600x400/?orenburg"], link: "https://ru.wikipedia.org/wiki/Оренбург"),
                Location(name: "Кемерово", cityName: "Кемерово", coordinate: CLLocationCoordinate2D(latitude: 55.3547, longitude: 86.0873), description: "Столица Кузбасса", imageName: ["https://source.unsplash.com/600x400/?kemerovo"], link: "https://ru.wikipedia.org/wiki/Кемерово"),
                Location(name: "Новокузнецк", cityName: "Новокузнецк", coordinate: CLLocationCoordinate2D(latitude: 53.7576, longitude: 87.1360), description: "Металлургический центр", imageName: ["https://source.unsplash.com/600x400/?novokuznetsk"], link: "https://ru.wikipedia.org/wiki/Новокузнецк"),
                Location(name: "Рязань", cityName: "Рязань", coordinate: CLLocationCoordinate2D(latitude: 54.6269, longitude: 39.6916), description: "Древний русский город", imageName: ["https://source.unsplash.com/600x400/?ryazan"], link: "https://ru.wikipedia.org/wiki/Рязань"),
                Location(name: "Астрахань", cityName: "Астрахань", coordinate: CLLocationCoordinate2D(latitude: 46.3479, longitude: 48.0336), description: "Город в дельте Волги", imageName: ["https://source.unsplash.com/600x400/?astrakhan"], link: "https://ru.wikipedia.org/wiki/Астрахань"),
                Location(name: "Пенза", cityName: "Пенза", coordinate: CLLocationCoordinate2D(latitude: 53.1951, longitude: 45.0183), description: "Город на Суре", imageName: ["https://source.unsplash.com/600x400/?penza"], link: "https://ru.wikipedia.org/wiki/Пенза"),
                Location(name: "Липецк", cityName: "Липецк", coordinate: CLLocationCoordinate2D(latitude: 52.6088, longitude: 39.5992), description: "Металлургический центр", imageName: ["https://source.unsplash.com/600x400/?lipetsk"], link: "https://ru.wikipedia.org/wiki/Липецк"),
                Location(name: "Киров", cityName: "Киров", coordinate: CLLocationCoordinate2D(latitude: 58.6036, longitude: 49.6680), description: "Город на Вятке", imageName: ["https://source.unsplash.com/600x400/?kirov"], link: "https://ru.wikipedia.org/wiki/Киров_(город)"),
                Location(name: "Чебоксары", cityName: "Чебоксары", coordinate: CLLocationCoordinate2D(latitude: 56.1463, longitude: 47.2511), description: "Столица Чувашии", imageName: ["https://source.unsplash.com/600x400/?cheboksary"], link: "https://ru.wikipedia.org/wiki/Чебоксары"),
                Location(name: "Тула", cityName: "Тула", coordinate: CLLocationCoordinate2D(latitude: 54.1930, longitude: 37.6175), description: "Оружейная столица", imageName: ["https://source.unsplash.com/600x400/?tula"], link: "https://ru.wikipedia.org/wiki/Тула"),
                Location(name: "Калининград", cityName: "Калининград", coordinate: CLLocationCoordinate2D(latitude: 54.7104, longitude: 20.4522), description: "Западный форпост России", imageName: ["https://source.unsplash.com/600x400/?kaliningrad"], link: "https://ru.wikipedia.org/wiki/Калининград"),
                Location(name: "Брянск", cityName: "Брянск", coordinate: CLLocationCoordinate2D(latitude: 53.2436, longitude: 34.3634), description: "Город партизанской славы", imageName: ["https://source.unsplash.com/600x400/?bryansk"], link: "https://ru.wikipedia.org/wiki/Брянск"),
                Location(name: "Курск", cityName: "Курск", coordinate: CLLocationCoordinate2D(latitude: 51.7304, longitude: 36.1926), description: "Город воинской славы", imageName: ["https://source.unsplash.com/600x400/?kursk"], link: "https://ru.wikipedia.org/wiki/Курск"),
                Location(name: "Магнитогорск", cityName: "Магнитогорск", coordinate: CLLocationCoordinate2D(latitude: 53.4072, longitude: 58.9790), description: "Металлургический гигант", imageName: ["https://source.unsplash.com/600x400/?magnitogorsk"], link: "https://ru.wikipedia.org/wiki/Магнитогорск"),
                Location(name: "Тверь", cityName: "Тверь", coordinate: CLLocationCoordinate2D(latitude: 56.8587, longitude: 35.9176), description: "Город на Волге", imageName: ["https://source.unsplash.com/600x400/?tver"], link: "https://ru.wikipedia.org/wiki/Тверь"),
                Location(name: "Ставрополь", cityName: "Ставрополь", coordinate: CLLocationCoordinate2D(latitude: 45.0445, longitude: 41.9691), description: "Ворота Кавказа", imageName: ["https://source.unsplash.com/600x400/?stavropol"], link: "https://ru.wikipedia.org/wiki/Ставрополь"),
                Location(name: "Сочи", cityName: "Сочи", coordinate: CLLocationCoordinate2D(latitude: 43.5855, longitude: 39.7231), description: "Курортная столица", imageName: ["https://source.unsplash.com/600x400/?sochi"], link: "https://ru.wikipedia.org/wiki/Сочи"),
                Location(name: "Белгород", cityName: "Белгород", coordinate: CLLocationCoordinate2D(latitude: 50.5953, longitude: 36.5873), description: "Город первого салюта", imageName: ["https://source.unsplash.com/600x400/?belgorod"], link: "https://ru.wikipedia.org/wiki/Белгород"),
                Location(name: "Нижний Тагил", cityName: "Нижний Тагил", coordinate: CLLocationCoordinate2D(latitude: 57.9101, longitude: 59.9813), description: "Горнозаводской центр", imageName: ["https://source.unsplash.com/600x400/?nizhny+tagil"], link: "https://ru.wikipedia.org/wiki/Нижний_Тагил"),
                Location(name: "Владимир", cityName: "Владимир", coordinate: CLLocationCoordinate2D(latitude: 56.1290, longitude: 40.4066), description: "Древняя столица Руси", imageName: ["https://source.unsplash.com/600x400/?vladimir"], link: "https://ru.wikipedia.org/wiki/Владимир"),
                Location(name: "Архангельск", cityName: "Архангельск", coordinate: CLLocationCoordinate2D(latitude: 64.5399, longitude: 40.5158), description: "Портовый город на Севере", imageName: ["https://source.unsplash.com/600x400/?arkhangelsk"], link: "https://ru.wikipedia.org/wiki/Архангельск"),
                Location(name: "Сургут", cityName: "Сургут", coordinate: CLLocationCoordinate2D(latitude: 61.2541, longitude: 73.3960), description: "Нефтяная столица", imageName: ["https://source.unsplash.com/600x400/?surgut"], link: "https://ru.wikipedia.org/wiki/Сургут"),
                Location(name: "Чита", cityName: "Чита", coordinate: CLLocationCoordinate2D(latitude: 52.0340, longitude: 113.5010), description: "Столица Забайкалья", imageName: ["https://source.unsplash.com/600x400/?chita"], link: "https://ru.wikipedia.org/wiki/Чита"),
                Location(name: "Калуга", cityName: "Калуга", coordinate: CLLocationCoordinate2D(latitude: 54.5138, longitude: 36.2612), description: "Колыбель космонавтики", imageName: ["https://source.unsplash.com/600x400/?kaluga"], link: "https://ru.wikipedia.org/wiki/Калуга"),
                Location(name: "Смоленск", cityName: "Смоленск", coordinate: CLLocationCoordinate2D(latitude: 54.7826, longitude: 32.0453), description: "Город-щит России", imageName: ["https://source.unsplash.com/600x400/?smolensk"], link: "https://ru.wikipedia.org/wiki/Смоленск"),
                Location(name: "Волжский", cityName: "Волжский", coordinate: CLLocationCoordinate2D(latitude: 48.7858, longitude: 44.7797), description: "Город-спутник Волгограда", imageName: ["https://source.unsplash.com/600x400/?volzhsky"], link: "https://ru.wikipedia.org/wiki/Волжский"),
                Location(name: "Саранск", cityName: "Саранск", coordinate: CLLocationCoordinate2D(latitude: 54.1874, longitude: 45.1839), description: "Столица Мордовии", imageName: ["https://source.unsplash.com/600x400/?saransk"], link: "https://ru.wikipedia.org/wiki/Саранск"),
                Location(name: "Череповец", cityName: "Череповец", coordinate: CLLocationCoordinate2D(latitude: 59.1216, longitude: 37.9035), description: "Металлургический центр", imageName: ["https://source.unsplash.com/600x400/?cherepovets"], link: "https://ru.wikipedia.org/wiki/Череповец"),
                Location(name: "Вологда", cityName: "Вологда", coordinate: CLLocationCoordinate2D(latitude: 59.2205, longitude: 39.8915), description: "Город кружев", imageName: ["https://source.unsplash.com/600x400/?vologda"], link: "https://ru.wikipedia.org/wiki/Вологда"),
                Location(name: "Орёл", cityName: "Орёл", coordinate: CLLocationCoordinate2D(latitude: 52.9703, longitude: 36.0639), description: "Город первого салюта", imageName: ["https://source.unsplash.com/600x400/?orel"], link: "https://ru.wikipedia.org/wiki/Орёл"),
                Location(name: "Якутск", cityName: "Якутск", coordinate: CLLocationCoordinate2D(latitude: 62.0278, longitude: 129.7315), description: "Столица Якутии", imageName: ["https://source.unsplash.com/600x400/?yakutsk"], link: "https://ru.wikipedia.org/wiki/Якутск"),
                Location(name: "Владикавказ", cityName: "Владикавказ", coordinate: CLLocationCoordinate2D(latitude: 43.0246, longitude: 44.6818), description: "Столица Северной Осетии", imageName: ["https://source.unsplash.com/600x400/?vladikavkaz"], link: "https://ru.wikipedia.org/wiki/Владикавказ"),
                Location(name: "Мурманск", cityName: "Мурманск", coordinate: CLLocationCoordinate2D(latitude: 68.9707, longitude: 33.0750), description: "Крупнейший порт Заполярья", imageName: ["https://source.unsplash.com/600x400/?murmansk"], link: "https://ru.wikipedia.org/wiki/Мурманск"),
                Location(name: "Кострома", cityName: "Кострома", coordinate: CLLocationCoordinate2D(latitude: 57.7679, longitude: 40.9269), description: "Ювелирная столица", imageName: ["https://source.unsplash.com/600x400/?kostroma"], link: "https://ru.wikipedia.org/wiki/Кострома"),
                Location(name: "Новороссийск", cityName: "Новороссийск", coordinate: CLLocationCoordinate2D(latitude: 44.7235, longitude: 37.7686), description: "Портовый город на Чёрном море", imageName: ["https://source.unsplash.com/600x400/?novorossiysk"], link: "https://ru.wikipedia.org/wiki/Новороссийск"),
                Location(name: "Химки", cityName: "Химки", coordinate: CLLocationCoordinate2D(latitude: 55.8887, longitude: 37.4304), description: "Город-спутник Москвы", imageName: ["https://source.unsplash.com/600x400/?khimki"], link: "https://ru.wikipedia.org/wiki/Химки"),
                Location(name: "Таганрог", cityName: "Таганрог", coordinate: CLLocationCoordinate2D(latitude: 47.2214, longitude: 38.9094), description: "Родина Чехова", imageName: ["https://source.unsplash.com/600x400/?taganrog"], link: "https://ru.wikipedia.org/wiki/Таганрог"),
                Location(name: "Стерлитамак", cityName: "Стерлитамак", coordinate: CLLocationCoordinate2D(latitude: 53.6306, longitude: 55.9306), description: "Химическая столица", imageName: ["https://source.unsplash.com/600x400/?sterlitamak"], link: "https://ru.wikipedia.org/wiki/Стерлитамак"),
                Location(name: "Петрозаводск", cityName: "Петрозаводск", coordinate: CLLocationCoordinate2D(latitude: 61.7849, longitude: 34.3469), description: "Столица Карелии", imageName: ["https://source.unsplash.com/600x400/?petrozavodsk"], link: "https://ru.wikipedia.org/wiki/Петрозаводск"),
                Location(name: "Нижневартовск", cityName: "Нижневартовск", coordinate: CLLocationCoordinate2D(latitude: 60.9397, longitude: 76.5694), description: "Нефтяная столица", imageName: ["https://source.unsplash.com/600x400/?nizhnevartovsk"], link: "https://ru.wikipedia.org/wiki/Нижневартовск"),
                Location(name: "Братск", cityName: "Братск", coordinate: CLLocationCoordinate2D(latitude: 56.1514, longitude: 101.6342), description: "Город энергетиков", imageName: ["https://source.unsplash.com/600x400/?bratsk"], link: "https://ru.wikipedia.org/wiki/Братск"),
                Location(name: "Дзержинск", cityName: "Дзержинск", coordinate: CLLocationCoordinate2D(latitude: 56.2377, longitude: 43.4597), description: "Химический центр", imageName: ["https://source.unsplash.com/600x400/?dzerzhinsk"], link: "https://ru.wikipedia.org/wiki/Дзержинск_(Нижегородская_область)"),
                Location(name: "Шахты", cityName: "Шахты", coordinate: CLLocationCoordinate2D(latitude: 47.7085, longitude: 40.2160), description: "Угольный центр", imageName: ["https://source.unsplash.com/600x400/?shakhty"], link: "https://ru.wikipedia.org/wiki/Шахты"),
                Location(name: "Орск", cityName: "Орск", coordinate: CLLocationCoordinate2D(latitude: 51.2293, longitude: 58.4750), description: "Промышленный центр", imageName: ["https://source.unsplash.com/600x400/?orsk"], link: "https://ru.wikipedia.org/wiki/Орск"),
                Location(name: "Нальчик", cityName: "Нальчик", coordinate: CLLocationCoordinate2D(latitude: 43.4853, longitude: 43.6071), description: "Столица Кабардино-Балкарии", imageName: ["https://source.unsplash.com/600x400/?nalchik"], link: "https://ru.wikipedia.org/wiki/Нальчик"),
                Location(name: "Сыктывкар", cityName: "Сыктывкар", coordinate: CLLocationCoordinate2D(latitude: 61.6688, longitude: 50.8354), description: "Столица Коми", imageName: ["https://source.unsplash.com/600x400/?syktyvkar"], link: "https://ru.wikipedia.org/wiki/Сыктывкар"),
                Location(name: "Нижнекамск", cityName: "Нижнекамск", coordinate: CLLocationCoordinate2D(latitude: 55.6340, longitude: 51.8160), description: "Нефтехимический центр", imageName: ["https://source.unsplash.com/600x400/?nizhnekamsk"], link: "https://ru.wikipedia.org/wiki/Нижнекамск"),
                Location(name: "Ангарск", cityName: "Ангарск", coordinate: CLLocationCoordinate2D(latitude: 52.5440, longitude: 103.9190), description: "Город нефтехимиков", imageName: ["https://source.unsplash.com/600x400/?angarsk"], link: "https://ru.wikipedia.org/wiki/Ангарск"),
                Location(name: "Старый Оскол", cityName: "Старый Оскол", coordinate: CLLocationCoordinate2D(latitude: 51.2981, longitude: 37.8350), description: "Горнорудный центр", imageName: ["https://source.unsplash.com/600x400/?stary+oskol"], link: "https://ru.wikipedia.org/wiki/Старый_Оскол"),
                Location(name: "Великий Новгород", cityName: "Великий Новгород", coordinate: CLLocationCoordinate2D(latitude: 58.5228, longitude: 31.2699), description: "Древняя столица Руси", imageName: ["https://source.unsplash.com/600x400/?veliky+novgorod"], link: "https://ru.wikipedia.org/wiki/Великий_Новгород"),
                Location(name: "Балашиха", cityName: "Балашиха", coordinate: CLLocationCoordinate2D(latitude: 55.8095, longitude: 37.9581), description: "Крупнейший подмосковный город", imageName: ["https://source.unsplash.com/600x400/?balashikha"], link: "https://ru.wikipedia.org/wiki/Балашиха"),
                Location(name: "Благовещенск", cityName: "Благовещенск", coordinate: CLLocationCoordinate2D(latitude: 50.2907, longitude: 127.5272), description: "Столица Амурской области", imageName: ["https://source.unsplash.com/600x400/?blagoveshchensk"], link: "https://ru.wikipedia.org/wiki/Благовещенск"),
                Location(name: "Прокопьевск", cityName: "Прокопьевск", coordinate: CLLocationCoordinate2D(latitude: 53.8606, longitude: 86.7183), description: "Угольный центр", imageName: ["https://source.unsplash.com/600x400/?prokopyevsk"], link: "https://ru.wikipedia.org/wiki/Прокопьевск"),
                Location(name: "Бийск", cityName: "Бийск", coordinate: CLLocationCoordinate2D(latitude: 52.5393, longitude: 85.2139), description: "Наукоград", imageName: ["https://source.unsplash.com/600x400/?biysk"], link: "https://ru.wikipedia.org/wiki/Бийск"),
                Location(name: "Энгельс", cityName: "Энгельс", coordinate: CLLocationCoordinate2D(latitude: 51.4850, longitude: 46.1163), description: "Город-спутник Саратова", imageName: ["https://source.unsplash.com/600x400/?engels"], link: "https://ru.wikipedia.org/wiki/Энгельс"),
                Location(name: "Рыбинск", cityName: "Рыбинск", coordinate: CLLocationCoordinate2D(latitude: 58.0486, longitude: 38.8584), description: "Город на Волге", imageName: ["https://source.unsplash.com/600x400/?rybinsk"], link: "https://ru.wikipedia.org/wiki/Рыбинск"),
                Location(name: "Северодвинск", cityName: "Северодвинск", coordinate: CLLocationCoordinate2D(latitude: 64.5625, longitude: 39.8183), description: "Центр атомного судостроения", imageName: ["https://source.unsplash.com/600x400/?severodvinsk"], link: "https://ru.wikipedia.org/wiki/Северодвинск"),
                Location(name: "Армавир", cityName: "Армавир", coordinate: CLLocationCoordinate2D(latitude: 45.0015, longitude: 41.1345), description: "Город на Кубани", imageName: ["https://source.unsplash.com/600x400/?armavir"], link: "https://ru.wikipedia.org/wiki/Армавир_(Россия)"),
                Location(name: "Подольск", cityName: "Подольск", coordinate: CLLocationCoordinate2D(latitude: 55.4311, longitude: 37.5457), description: "Промышленный центр Подмосковья", imageName: ["https://source.unsplash.com/600x400/?podolsk"], link: "https://ru.wikipedia.org/wiki/Подольск"),
                Location(name: "Королёв", cityName: "Королёв", coordinate: CLLocationCoordinate2D(latitude: 55.9167, longitude: 37.8167), description: "Космическая столица", imageName: ["https://source.unsplash.com/600x400/?korolev"], link: "https://ru.wikipedia.org/wiki/Королёв"),
                Location(name: "Южно-Сахалинск", cityName: "Южно-Сахалинск", coordinate: CLLocationCoordinate2D(latitude: 46.9591, longitude: 142.7380), description: "Столица Сахалина", imageName: ["https://source.unsplash.com/600x400/?yuzhno+sakhalinsk"], link: "https://ru.wikipedia.org/wiki/Южно-Сахалинск"),
                Location(name: "Люберцы", cityName: "Люберцы", coordinate: CLLocationCoordinate2D(latitude: 55.6784, longitude: 37.8937), description: "Город-спутник Москвы", imageName: ["https://source.unsplash.com/600x400/?lyubertsy"], link: "https://ru.wikipedia.org/wiki/Люберцы"),
                Location(name: "Мытищи", cityName: "Мытищи", coordinate: CLLocationCoordinate2D(latitude: 55.9105, longitude: 37.7364), description: "Город в Подмосковье", imageName: ["https://source.unsplash.com/600x400/?mytishchi"], link: "https://ru.wikipedia.org/wiki/Мытищи"),
                Location(name: "Ковров", cityName: "Ковров", coordinate: CLLocationCoordinate2D(latitude: 56.3572, longitude: 41.3192), description: "Оружейный центр", imageName: ["https://source.unsplash.com/600x400/?kovrov"], link: "https://ru.wikipedia.org/wiki/Ковров"),
                Location(name: "Хасавюрт", cityName: "Хасавюрт", coordinate: CLLocationCoordinate2D(latitude: 43.2505, longitude: 46.5852), description: "Город в Дагестане", imageName: ["https://source.unsplash.com/600x400/?khasavyurt"], link: "https://ru.wikipedia.org/wiki/Хасавюрт"),
                Location(name: "Новочеркасск", cityName: "Новочеркасск", coordinate: CLLocationCoordinate2D(latitude: 47.4184, longitude: 40.0935), description: "Столица донского казачества", imageName: ["https://source.unsplash.com/600x400/?novocherkassk"], link: "https://ru.wikipedia.org/wiki/Новочеркасск"),
                Location(name: "Серпухов", cityName: "Серпухов", coordinate: CLLocationCoordinate2D(latitude: 54.9222, longitude: 37.4136), description: "Город в Подмосковье", imageName: ["https://source.unsplash.com/600x400/?serpukhov"], link: "https://ru.wikipedia.org/wiki/Серпухов"),
                Location(name: "Первоуральск", cityName: "Первоуральск", coordinate: CLLocationCoordinate2D(latitude: 56.9081, longitude: 59.9429), description: "Металлургический центр", imageName: ["https://source.unsplash.com/600x400/?pervouralsk"], link: "https://ru.wikipedia.org/wiki/Первоуральск"),
                Location(name: "Нефтеюганск", cityName: "Нефтеюганск", coordinate: CLLocationCoordinate2D(latitude: 61.0882, longitude: 72.6164), description: "Нефтяной центр", imageName: ["https://source.unsplash.com/600x400/?nefteyugansk"], link: "https://ru.wikipedia.org/wiki/Нефтеюганск"),
                Location(name: "Димитровград", cityName: "Димитровград", coordinate: CLLocationCoordinate2D(latitude: 54.2169, longitude: 49.6183), description: "Атомный центр", imageName: ["https://source.unsplash.com/600x400/?dimitrovgrad"], link: "https://ru.wikipedia.org/wiki/Димитровград"),
                Location(name: "Каменск-Уральский", cityName: "Каменск-Уральский", coordinate: CLLocationCoordinate2D(latitude: 56.4149, longitude: 61.9189), description: "Металлургический центр", imageName: ["https://source.unsplash.com/600x400/?kamensk+uralsky"], link: "https://ru.wikipedia.org/wiki/Каменск-Уральский"),
                Location(name: "Орехово-Зуево", cityName: "Орехово-Зуево", coordinate: CLLocationCoordinate2D(latitude: 55.8067, longitude: 38.9618), description: "Текстильный центр", imageName: ["https://source.unsplash.com/600x400/?orekhovo+zuevo"], link: "https://ru.wikipedia.org/wiki/Орехово-Зуево"),
                Location(name: "Дербент", cityName: "Дербент", coordinate: CLLocationCoordinate2D(latitude: 42.0578, longitude: 48.2776), description: "Древнейший город России", imageName: ["https://source.unsplash.com/600x400/?derbent"], link: "https://ru.wikipedia.org/wiki/Дербент"),
                Location(name: "Черкесск", cityName: "Черкесск", coordinate: CLLocationCoordinate2D(latitude: 44.2269, longitude: 42.0468), description: "Столица Карачаево-Черкесии", imageName: ["https://source.unsplash.com/600x400/?cherkessk"], link: "https://ru.wikipedia.org/wiki/Черкесск"),
                Location(name: "Невинномысск", cityName: "Невинномысск", coordinate: CLLocationCoordinate2D(latitude: 44.6333, longitude: 41.9333), description: "Химический центр", imageName: ["https://source.unsplash.com/600x400/?nevinnomyssk"], link: "https://ru.wikipedia.org/wiki/Невинномысск"),
                Location(name: "Кисловодск", cityName: "Кисловодск", coordinate: CLLocationCoordinate2D(latitude: 43.9053, longitude: 42.7167), description: "Курортный город", imageName: ["https://source.unsplash.com/600x400/?kislovodsk"], link: "https://ru.wikipedia.org/wiki/Кисловодск"),
                Location(name: "Новошахтинск", cityName: "Новошахтинск", coordinate: CLLocationCoordinate2D(latitude: 47.7576, longitude: 39.9364), description: "Угольный центр", imageName: ["https://source.unsplash.com/600x400/?novoshakhtinsk"], link: "https://ru.wikipedia.org/wiki/Новошахтинск"),
                Location(name: "Йошкар-Ола", cityName: "Йошкар-Ола", coordinate: CLLocationCoordinate2D(latitude: 56.6320, longitude: 47.8959), description: "Столица Марий Эл", imageName: ["https://source.unsplash.com/600x400/?yoshkar+ola"], link: "https://ru.wikipedia.org/wiki/Йошкар-Ола"),
                Location(name: "Ноябрьск", cityName: "Ноябрьск", coordinate: CLLocationCoordinate2D(latitude: 63.2018, longitude: 75.4510), description: "Нефтяной центр", imageName: ["https://source.unsplash.com/600x400/?noyabrsk"], link: "https://ru.wikipedia.org/wiki/Ноябрьск"),

        
    ]
    
}
